
receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  awss3:
    s3uploader:
      region: eu-west-1
      s3_bucket: "885967231520-indigo-otel-trace"
      s3_prefix: "trace-pb"
    marshaler: otlp_proto


service:
  pipelines:
    traces/s3:
      receivers: [otlp]
      exporters: [awss3]

